config/routes.rb
Rails.application.routes.draw do
  resources :first_world_problems

  root :to => 'first_world_problems#index'
end

app/models/first_world_problem.rb
class FirstWorldProblem < ActiveRecord::Base

  def create_problem(message)
    problem = FirstWorldProblem.create(problem: message)
  end

  def get_random_response
    responses = []
    file_path = File.join(Rails.root, 'responses.txt')
    texts = File.read(file_path).split /[\n]/
    texts.shuffle[0] 
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/first_world_problems_controller.rb
class FirstWorldProblemsController < ApplicationController
  before_action :set_first_world_problem, only: [:show, :edit, :update, :destroy]

  # GET /first_world_problems
  # GET /first_world_problems.json
  def index
    @first_world_problems = FirstWorldProblem.all
    @first_world_problem = FirstWorldProblem.new
  end

  # GET /first_world_problems/1
  # GET /first_world_problems/1.json
  def show
    @first_world_problems = FirstWorldProblem.all
  end

  # GET /first_world_problems/new
  def new
    @first_world_problem = FirstWorldProblem.new
  end

  # GET /first_world_problems/1/edit
  def edit
  end

  # POST /first_world_problems
  # POST /first_world_problems.json
  def create
    @first_world_problem = FirstWorldProblem.new(first_world_problem_params)

    respond_to do |format|
      if @first_world_problem.save
        format.html { redirect_to @first_world_problem, notice: 'First world problem was successfully created.' }
        format.json { render :show, status: :created, location: @first_world_problem }
      else
        format.html { render :new }
        format.json { render json: @first_world_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_world_problems/1
  # PATCH/PUT /first_world_problems/1.json
  def update
    respond_to do |format|
      if @first_world_problem.update(first_world_problem_params)
        format.html { redirect_to @first_world_problem, notice: 'First world problem was successfully updated.' }
        format.json { render :show, status: :ok, location: @first_world_problem }
      else
        format.html { render :edit }
        format.json { render json: @first_world_problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_world_problems/1
  # DELETE /first_world_problems/1.json
  def destroy
    @first_world_problem.destroy
    respond_to do |format|
      format.html { redirect_to first_world_problems_url, notice: 'First world problem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_world_problem
      @first_world_problem = FirstWorldProblem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_world_problem_params
      params.require(:first_world_problem).permit(:problem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_world_problems_helper.rb
module FirstWorldProblemsHelper
end

app/views/first_world_problems/_form.html.erb
<%= form_for(@first_world_problem) do |f| %>
  <% if @first_world_problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first_world_problem.errors.count, "error") %> prohibited this first_world_problem from being saved:</h2>

      <ul>
      <% @first_world_problem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<center>
  <div class="field">
    <%= f.text_area :problem, :rows => 8, :cols => 50, :id => "problem", :placeholder => "Your problem here..." %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
</center>
<% end %>

app/views/first_world_problems/edit.html.erb
<h1>Editing first_world_problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @first_world_problem %> |
<%= link_to 'Back', first_world_problems_path %>

app/views/first_world_problems/index.html.erb
<h1>#FirstWorldProblems</h1>
<div class="main_area">

  <%= render 'form' %>

  <br/>
  <td ><%= link_to 'See other #FirstWorldProblems', method: :show_all, :class => "link" %></td>
</div>

app/views/first_world_problems/new.html.erb
<h1>New first_world_problem</h1>

<%= render 'form' %>

<%= link_to 'Back', first_world_problems_path %>

app/views/first_world_problems/show.html.erb
<h1>#FirstWorldProblems</h1>
<p id="notice"><%= notice %></p>
<p>
  <strong>Problem:</strong>
  <%= @first_world_problem.problem %>
</p>

<div class="row">
<% @first_world_problems.each do |first_world_problem| %>
<div class="col-md-4">
	<div class="posted_problem">
		<div class="problem_content"><%= first_world_problem.problem %></div>
		<%= link_to 'Show', first_world_problem %>
		<%= link_to 'Edit', edit_first_world_problem_path(first_world_problem) %>
		<%= link_to 'Destroy', first_world_problem, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
</br>
</div>
<% end %>
</div>

<%= link_to 'Edit', edit_first_world_problem_path(@first_world_problem) %> |
<%= link_to 'Back', first_world_problems_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FWP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Shadows+Into+Light|Indie+Flower|Poiret+One|Crafty+Girls|Waiting+for+the+Sunrise' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>